apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${ISSUER_APP_NAME}-postgres-data
  namespace: ${ISSUER_NAMESPACE}
spec:
  storageClassName: ${STORAGECLASS}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

