apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
  namespace: ${ISSUER_NAMESPACE}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${ISSUER_DOCKER_REGISTRY_CREDENTIALS}
---

