apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${ISSUER_APP_NAME}-postgres
  name: ${ISSUER_APP_NAME}-postgres
  namespace: ${ISSUER_NAMESPACE}
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: ${ISSUER_APP_NAME}-postgres
---

